"""initial

Revision ID: 13c9222d5cfe
Revises: 
Create Date: 2026-06-24 13:21:04.728673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c9222d5cfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('refresh_jti', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_jti')
    )
    op.create_table('workspaces',
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('deployment_mode', sa.Text(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('cloud_workspace_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("deployment_mode IN ('local', 'cloud')", name='ck_workspace_deployment_mode'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_branch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_types',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_entity_types_workspace_name')
    )
    op.create_table('files',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_provider', sa.Text(), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_reports',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.Column('orphan_count', sa.Integer(), nullable=True),
    sa.Column('stale_count', sa.Integer(), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_materializations',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('graph_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_operations',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operation_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('client_clock', sa.BigInteger(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_tags_workspace_name')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'editor', 'viewer')", name='ck_workspace_member_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_merges',
    sa.Column('source_branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.CheckConstraint('source_branch_id != target_branch_id', name='no_self_merge'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('property_type', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', 'entity_type_id', name='uq_properties_workspace_name_type')
    )
    op.create_table('snapshots',
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('position', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'position', name='uq_blocks_entity_position')
    )
    op.create_table('changesets',
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_property_values',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('property_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_tags',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merge_conflicts',
    sa.Column('merge_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conflict_type', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merge_id'], ['branch_merges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('source_entity_id != target_entity_id', name='no_self_relation'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relation_type', name='unique_relation')
    )
    op.create_table('activity_logs',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_versions',
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('changeset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('parent_comment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('embedding', app.models.types.Vector(dim=1024), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_events',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('changeset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_files',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'file_id', name='uq_entity_files_active')
    )
    op.create_table('entity_versions',
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('changeset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_documents',
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('block_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('search_vector', app.models.types.TSVectorType(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_branch_heads',
    sa.Column('branch_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('base_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['entity_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_version_id'], ['entity_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'entity_id', name='uq_entity_branch_heads')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_branch_heads')
    op.drop_table('search_documents')
    op.drop_table('entity_versions')
    op.drop_table('entity_files')
    op.drop_table('entity_events')
    op.drop_table('embeddings')
    op.drop_table('comments')
    op.drop_table('block_versions')
    op.drop_table('activity_logs')
    op.drop_table('relations')
    op.drop_table('notifications')
    op.drop_table('merge_conflicts')
    op.drop_table('entity_tags')
    op.drop_table('entity_property_values')
    op.drop_table('changesets')
    op.drop_table('blocks')
    op.drop_table('snapshots')
    op.drop_table('properties')
    op.drop_table('entities')
    op.drop_table('branch_merges')
    op.drop_table('workspace_members')
    op.drop_table('tags')
    op.drop_table('sync_operations')
    op.drop_table('jobs')
    op.drop_table('graph_materializations')
    op.drop_table('governance_reports')
    op.drop_table('files')
    op.drop_table('entity_types')
    op.drop_table('branches')
    op.drop_table('workspaces')
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
